// <auto-generated />
using AngularTechTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularTechTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220218183814_CreateEmployeeTablesAndDataSeeding")]
    partial class CreateEmployeeTablesAndDataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AngularTechTest.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT",
                            Name = "Jhon",
                            Salary = 100000
                        },
                        new
                        {
                            Id = 2,
                            Department = "HR",
                            Name = "Rimi",
                            Salary = 200000
                        },
                        new
                        {
                            Id = 3,
                            Department = "Operation",
                            Name = "Jim",
                            Salary = 50000
                        },
                        new
                        {
                            Id = 4,
                            Department = "IT",
                            Name = "Dev",
                            Salary = 150000
                        },
                        new
                        {
                            Id = 5,
                            Department = "HR",
                            Name = "Sarah",
                            Salary = 60000
                        },
                        new
                        {
                            Id = 6,
                            Department = "IT",
                            Name = "Steve",
                            Salary = 170000
                        },
                        new
                        {
                            Id = 7,
                            Department = "Operation",
                            Name = "Henry",
                            Salary = 60000
                        },
                        new
                        {
                            Id = 8,
                            Department = "IT",
                            Name = "Tony",
                            Salary = 80000
                        },
                        new
                        {
                            Id = 9,
                            Department = "IT",
                            Name = "Ema",
                            Salary = 85000
                        },
                        new
                        {
                            Id = 10,
                            Department = "Operation",
                            Name = "Dani",
                            Salary = 90000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
